Unit ALM304;
// HPC_201602_ALM 30/04/2016 Entrega a Calidad

Interface

Uses
   Windows, Messages, SysUtils, Classes, Graphics, Controls, Forms, Dialogs,
   ComCtrls;

Type
   TFConsulta2 = Class(TForm)
      pgctlUno: TPageControl;
      TabSheet1: TTabSheet;
   Private
    { Private declarations }
   Public
    { Public declarations }
   End;

Var
   FConsulta2: TFConsulta2;

Implementation

{$R *.DFM}

End.

